### ISSUE TITLE
Fundamental misunderstanding of TimeInterval

### ISSUE THREAD

**Issue by orj** [dominicegginton/nanoseconds#4]
Unless I'm reading the the code for this project wrong it suggests you have a fundamental misunderstanding of the `TimeInterval` type in Swift.

`TimeInterval` is [measured in seconds](https://developer.apple.com/documentation/foundation/timeinterval).  So if you wanted to initialise a `TimeInterval` as a specific number of seconds you would initialise it directly, eg:

    var seconds: TimeInterval = 10 // 10 seconds.

Your code instead has this:

    public init (seconds: Double) { self = seconds * 1e+9 }

Which multiplies the stored `TimeInterval` by 1_000_000_000.  Making the value stored be some multiple of a billion seconds. If you then passed this value to any Swift API expecting a `TimeInterval` you would be waiting a __very long time__.

I recommend you re-evaluate your assumptions here.  Or better yet adopt the new iOS 16 Clock APIs.

If your intention was to create a `Nanosecond` type this logic would make sense.  But you shouldn't use a `Double` (aka `TimeInterval`) for that. Instead look at `Int64`.

**Comment by dominicegginton** [comment]
Many thanks for taking the time to read the library code and write a helpful issue pointing out my misunderstanding of `TimeInterval`.  I have released version [1.1.2](https://github.com/dominicegginton/nanoseconds/releases/tag/1.1.2) which should address these issues.
