### ISSUE TITLE
Subtraction is not returning reasonable values

### ISSUE THREAD

**Issue by markjaquith** [dominicegginton/nanoseconds#5]
There don't seem to be unit tests that check that the subtraction values are reasonable. I had my own tests in my app, and sleeping for two seconds doesn't yield a difference greater than one second.

<img width="951" alt="CleanShot 2023-06-20 at 01 49 56@2x" src="https://github.com/dominicegginton/nanoseconds/assets/353790/fde1927b-9d9c-4dd1-9d67-df1f48e3c576">

```swift
let before = Now()
sleep(2)
let after = Now()
XCTAssertGreaterThan((after - before).seconds, 1)
// XCTAssertGreaterThan failed: ("0.048024575") is not greater than ("1.0")
```

**Comment by dominicegginton** [comment]
Many thanks for opening an issue. I was unable to replicate the issue you are running into here.

I have replicated your test case [here](https://github.com/dominicegginton/nanoseconds/blob/subtraction-issue/Tests/NanosecondsTests/Substraction.swift#L5-L10), however, it passes both locally and in [CI](https://github.com/dominicegginton/nanoseconds/actions/runs/5912272097). Are you able to provide any more information on the use case of **nanoseconds**?

**Comment by dominicegginton** [comment]
@markjaquith I'm going to close this due to inactivity but feel free to open again if you still feel as tho there is an issue to be addressed.
